### ISSUE TITLE
Add back windows to CI

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/kissim_app#3]
Removed windows from CI, which fails when we load structures in `nglview` based on a text string (`add_component`). The text string is handled as path, which cannot be longer than 250 characters under windows.

`ValueError: stat: path too long for Windows`

https://github.com/volkamerlab/kissim_app/pull/2/checks?check_run_id=1870774017

**Comment by jaimergp** [comment]
This happens because `nglview` will check if the string you passed is a valid file path first (which might not be the case, because it's a block). You can work around this issue by wrapping your string in a `io.StringIO` object, I believe!
